name: Build and Push Docker Image

on: [push]

env:
  REGISTRY: docker.io
  IMAGE_NAME: volvram/docker-ci-cd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/docker-ci-cd:latest

      - name: Test
        run: docker run -d --name test-container ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest docker exec test-container curl -s http://localhost:3000 | grep "Hello from" || echo "Test failed" docker stop test-container