name: Docker Compose CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker and Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Start containers with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Verify services
        run: |
          docker ps -a
          curl --retry 5 --retry-delay 3 --retry-all-errors http://localhost:3001